python3 main.py compiler/test_files/quickSort.manchas
python3 main.py compiler/test_files/factorialCyclic.manchas
python3 main.py compiler/test_files/factorialRecursive.manchas
python3 main.py compiler/test_files/fibonacciCyclic.manchas
python3 main.py compiler/test_files/fibonacciRecursive.manchas
python3 main.py compiler/test_files/find.manchas
python3 main.py compiler/test_files/arrayOperations.manchas
python3 main.py compiler/test_files/myRLike.manchas
python3 main.py compiler/test_files/statistics.manchas